version: '3'

services:

  php-fpm:
    build: ./docker/build/php-fpm
    image: ${GLOBAL_NAME}/php-fpm
    container_name: ${COMPOSE_PROJECT_NAME}_php-fpm
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    networks:
      - public
      - default
    volumes:
      - ${PWD}/app:/app

  nginx:
    build: ./docker/build/nginx
    image: ${GLOBAL_NAME}/nginx
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    volumes:
    - ${PWD}/app:/app
    ports:
      - ${NGINX_PORT}:80
    networks:
      - public
      - default

networks:
  public:
    external:
      name: custom_net
  default:
    external: false
